#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  app_t10.py
#  
#  Copyright 2022 Vitória <Vitória@DESKTOP-8NUNN4I>
# 
# Aplicação
import mod_t10

def main():
	arqIn = input()
	arqOut = input()
	
	data = open(arqIn, "r")
	escrita = open(arqOut, "w")
	
	# Chamando as funções
	aux = mod_t10.valores(data)
	mod_t10.atualiza_Dicionario(aux)
	mod_t10.serializa(aux)
	mod_t10.imprima(aux)
	mod_t10.imprimaCon(escrita, aux)
	
	# Fechando os arquivos de entrada e saída
	data.close()
	escrita.close()
	
if __name__ == "__main__":
	main()


