#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  mod_apnp3.py
#  
#  Copyright 2021 Vitória <Vitória@DESKTOP-8NUNN4I>
#  
#  imc.py
#  Copyright 2021
#  Autora: Vitória Isabel Lemos de Mattos
#  Matricula: 20201tiimi0195
#
############################
# Código fonte em Python 3
###########################

"""
Este programa calcula o Índice de Massa Corporal e retorna o valor arredondado.
"""

#Importando a função
from app_apnp3 import mod_apnp3

def main():
	#Declaração de variáveis
	p = float(0.0)
	a = float(0.0)

	#Entrada de dados
	p = float(input())
	a = float(input())

	#Invocação da função imc
	x = mod_apnp3(p,a)

	#Saída
	print(f"P={p:.2f} A={a:.2f} IMC={x:.2f}") 
	return 0

if __name__ == '__main__':

	#invocação da função main

	main()
