#!/usr/bin/env python3
# -- coding: utf-8 --
#
#  apnp6.py
#
#  Copyright 2021
#  Autor: Vitória Isabel Lemos de Mattos
#  Matricula: 20201tiimi0195
#
#  Este programa:
#  Produz e
#  Retorna como saída strings contendo os padrões identificados pelas letras de a) a f)

###########################
#Código fonte em Python 3
###########################

def f_geraDesenho1(letra): 
	# Variaveis
	linhas = str("")

	# Processamento 
	for _ in range(6):
		linhas += letra * 6 + "\n"

	# Saída
	return linhas 

def f_geraDesenho2(letra):
	# Variaveis
	linhas = str("")
	i = int(0)

	# Processamento 
	for i in range(1,7):
		linhas += letra * i + "\n"

	# Saída 
	return linhas

def f_geraDesenho3(letra):
	# Variáveis 
	linhas = str("")
	espacos = str(" ")
	i = int(0)
	aux = int(5)

	# Processamento
	for i in range(1,7):
		linhas += espacos * aux + letra*i + "\n"
		aux -= 1

	# Saída
	return linhas

def f_geraDesenho4(letra):
	# Variáveis 
	linhas = str("") 
	espacos = str(" ")
	i = int(0)
	aux = int(3)

	# Processamento
	for i in range(1, 8, 2): #começa no 1, termina antes de chegar no 8 e soma de 2 
		linhas += espacos * aux + letra * i + espacos * aux + '\n'
		aux -= 1

	aux = 1
	for i in range(5, 0, -2):
		linhas +=  espacos * aux + letra * i + espacos * aux + '\n'
		aux += 1

	# Saída
	return linhas

def f_geraDesenho5(letra):
	# Variáveis
	linhas = str("")

	# Processamento
	for i in range(6, 0, -1):
		linhas += letra * i + "\n"

	# Saída
	return linhas

def f_geraDesenho6(letra):
	# Variaveis
	linhas = str("")
	espacos = str(" ")
	i = int(0)
	aux = int(5)

	# Processamento
	for i in range(6, 0, -1):
		linhas += espacos * aux + letra*i + "n" #pontapé
		aux -= 1

	# Saída 
	return linhas

def f_imprimePadrao(letra,opcao):
	# Processamento
	if opcao == "a":
		padrao = f_geraDesenho1(letra)

	elif opcao == "b": #uso do elif 
		padrao = f_geraDesenho2(letra)

	elif opcao == "c":
		padrao = f_geraDesenho3(letra)

	elif opcao == "d":
		padrao = f_geraDesenho4(letra)

	elif opcao == "e":
		padrao = f_geraDesenho5(letra)

	elif opcao == "f":
		padrao = f_geraDesenho6(letra)

	# Saída 
	return padrao
