#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  apnp1.py
#
#  Copyright 2021
#  Autor: Vitória Isabel Lemos de Mattos
#  Matricula: 20201tiimi0195
#
#  Este programa:
#  Lê um numero no formato MDC e escreve no formato UDC

def main():

#Declaração de variáveis
  n = int(0)
  u = int(0)
  d = int(0)
  c = int(0)
  m = int(0)

#Entrada de dados
n = int(input())
#Processamento

c = n // 100 % 10
d = n // 10 % 10
u = n // 1 % 10
m = u*100 + d*10 + c

#Saída
print("N =",n, "-> M =", m)
